server:
  port: 80


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?serverTimezone=UTC&useSSL=false
      username: root
      password: root
  main:
    banner-mode: off

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: deleted
      table-prefix: tbl_

  #      输出sql信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


